### ISSUE TITLE
Click handler doesn't work in safari

### ISSUE THREAD

**Issue by dthorne** [fs-webdev/dialog-el#11]
I'm having an issue with <fs-dialog> in safari. At `fs-dialog.html:411` it tries to get `e.path` and it's undefined in Safari. According to http://stackoverflow.com/questions/26195091/determine-event-path-in-dom-event-bubbling it may be a problem with shady-dom vs Shadow Dom. I'm not sure that there is a different way to get the event propagation path without this. You can see this now at https://beta.familysearch.org/tree/v8/person/KWJ2-RVQ/labels if you click "attach label" -> "War of 1812"

**Comment by tylergraf** [comment]
Yeah, `e.path` is basically only supported by Chrome. I looked into it a little bit, but didn't get far.
